// <auto-generated/>
using ApiSdk.GetData.Sequence;
using ApiSdk.GetData.Track;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ApiSdk.GetData {
    /// <summary>
    /// Builds and executes requests for operations under \getData
    /// </summary>
    public class GetDataRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The sequence property</summary>
        public SequenceRequestBuilder Sequence
        {
            get => new SequenceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The track property</summary>
        public TrackRequestBuilder Track
        {
            get => new TrackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="GetDataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetDataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/getData", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="GetDataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetDataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/getData", rawUrl)
        {
        }
    }
}
