/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { SequenceRequestBuilderRequestsMetadata, type SequenceRequestBuilder } from './sequence/';
// @ts-ignore
import { TrackRequestBuilderRequestsMetadata, type TrackRequestBuilder } from './track/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /getData
 */
export interface GetDataRequestBuilder extends BaseRequestBuilder<GetDataRequestBuilder> {
    /**
     * The sequence property
     */
    get sequence(): SequenceRequestBuilder;
    /**
     * The track property
     */
    get track(): TrackRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const GetDataRequestBuilderUriTemplate = "{+baseurl}/getData";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const GetDataRequestBuilderNavigationMetadata: Record<Exclude<keyof GetDataRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    sequence: {
        requestsMetadata: SequenceRequestBuilderRequestsMetadata,
    },
    track: {
        requestsMetadata: TrackRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
