/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /list/schema
 */
export interface SchemaRequestBuilder extends BaseRequestBuilder<SchemaRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     get(requestConfiguration?: RequestConfiguration<SchemaRequestBuilderGetQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SchemaRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface SchemaRequestBuilderGetQueryParameters {
    genome?: string;
    hubUrl?: string;
    track?: string;
}
/**
 * Uri template for the request builder.
 */
export const SchemaRequestBuilderUriTemplate = "{+baseurl}/list/schema?genome={genome}&track={track}{&hubUrl*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const SchemaRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SchemaRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
