// <auto-generated/>
using ApiSdk.List.Chromosomes;
using ApiSdk.List.Files;
using ApiSdk.List.HubGenomes;
using ApiSdk.List.PublicHubs;
using ApiSdk.List.Schema;
using ApiSdk.List.Tracks;
using ApiSdk.List.UcscGenomes;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ApiSdk.List {
    /// <summary>
    /// Builds and executes requests for operations under \list
    /// </summary>
    public class ListRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The chromosomes property</summary>
        public ChromosomesRequestBuilder Chromosomes
        {
            get => new ChromosomesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public FilesRequestBuilder Files
        {
            get => new FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hubGenomes property</summary>
        public HubGenomesRequestBuilder HubGenomes
        {
            get => new HubGenomesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The publicHubs property</summary>
        public PublicHubsRequestBuilder PublicHubs
        {
            get => new PublicHubsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The schema property</summary>
        public SchemaRequestBuilder Schema
        {
            get => new SchemaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tracks property</summary>
        public TracksRequestBuilder Tracks
        {
            get => new TracksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ucscGenomes property</summary>
        public UcscGenomesRequestBuilder UcscGenomes
        {
            get => new UcscGenomesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="ListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/list", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/list", rawUrl)
        {
        }
    }
}
