/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /getData/track
 */
export interface TrackRequestBuilder extends BaseRequestBuilder<TrackRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     get(requestConfiguration?: RequestConfiguration<TrackRequestBuilderGetQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<TrackRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface TrackRequestBuilderGetQueryParameters {
    chrom?: string;
    end?: number;
    genome?: string;
    hubUrl?: string;
    jsonOutputArrays?: boolean;
    maxItemsOutput?: number;
    start?: number;
    track?: string;
}
/**
 * Uri template for the request builder.
 */
export const TrackRequestBuilderUriTemplate = "{+baseurl}/getData/track?genome={genome}&track={track}{&chrom*,end*,hubUrl*,jsonOutputArrays*,maxItemsOutput*,start*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const TrackRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TrackRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
