/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /getData/sequence
 */
export interface SequenceRequestBuilder extends BaseRequestBuilder<SequenceRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     get(requestConfiguration?: RequestConfiguration<SequenceRequestBuilderGetQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SequenceRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface SequenceRequestBuilderGetQueryParameters {
    chrom?: string;
    end?: number;
    genome?: string;
    hubUrl?: string;
    start?: number;
}
/**
 * Uri template for the request builder.
 */
export const SequenceRequestBuilderUriTemplate = "{+baseurl}/getData/sequence?chrom={chrom}&genome={genome}{&end*,hubUrl*,start*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const SequenceRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SequenceRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
