/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota

export type Category = (typeof CategoryObject)[keyof typeof CategoryObject];
export type Format = (typeof FormatObject)[keyof typeof FormatObject];
export const CategoryObject = {
    HelpDocs: "helpDocs",
    PublicHubs: "publicHubs",
    TrackDb: "trackDb",
} as const;
export const FormatObject = {
    Text: "text",
} as const;
/* tslint:enable */
/* eslint-enable */
