// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models {
    #pragma warning disable CS1591
    public enum Category
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "helpDocs")]
        #pragma warning disable CS1591
        HelpDocs,
        #pragma warning restore CS1591
        [EnumMember(Value = "publicHubs")]
        #pragma warning disable CS1591
        PublicHubs,
        #pragma warning restore CS1591
        [EnumMember(Value = "trackDb")]
        #pragma warning disable CS1591
        TrackDb,
        #pragma warning restore CS1591
    }
}
