// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models {
    #pragma warning disable CS1591
    public enum Format
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
    }
}
